spring:
  # JDBC
  datasource:
    url: jdbc:mysql://47.104.189.214:3306/hxy?characterEncoding=UTF-8&useSSL=false
    username: root
    password: abc321@JG
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jackson: 
    date-format: yyyy-MM-dd HH:mm:ss
  jmx:
    enabled: false

  # REDIS
  redis:
    host: 47.104.189.214
    port: 6789
    password: JGtest123
    timeout: 0
    expire: 1800 #30分钟
    pool:
      max-active: 18
      max-idle: 18
      max-wait: -1
      min-idle: 0
logging:
  level:
    tk.mybatis: debug
    com.simple.mapper: debug
fdfs:
  soTimeout: 6000
  connectTimeout: 6000
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    - 39.106.160.245:22122
